### PR TITLE
added proper templating section

### PR DESCRIPTION
**Pull request by g0rgamesh**

### CODE REVIEW

**Review by jovial — APPROVED** [review]
Seems legit to me

**Review by JohnGarbutt — COMMENTED** [review]
So the dashboard here is for use with the import command, and that works and has been tested.

With kolla wee push it in via disk. Don't we need to update ${DS_PROMETHEUS} as well to make that work?

**Comment by g0rgamesh** [comment]
> So the dashboard here is for use with the import command, and that works and has been tested.
> 
> With kolla wee push it in via disk. Don't we need to update ${DS_PROMETHEUS} as well to make that work?

It's been tested without updating ${DS_PROMETHEUS}, and it worked.

**Comment by JohnGarbutt** [comment]
@g0rgamesh have you tested it still work via the UI when you import it please?

**Pull request merged**
