### PR TITLE
Some fixes for CLI use

### PR DESCRIPTION
**Pull request by markgoddard**

### CODE REVIEW

**Comment by markgoddard** [comment]
How about it?

**Comment by markgoddard** [comment]
WDYT @JohnGarbutt ?

**Comment by JohnGarbutt** [comment]
honestly, the CLI I was going to ripe out as dead code, if this helps make it work that that sounds good.

**Comment by JohnGarbutt** [comment]
Mostly I have only been using this file recently, which is fairly standalone: https://github.com/stackhpc/os-capacity/blob/master/os_capacity/prometheus.py

Not had time to tidy up the rest of it.

**Pull request merged**
